### ISSUE TITLE
hangs?

### ISSUE THREAD

**Issue by ralyodio** [jakub-g/biased-opener#1] opened 2015-04-12 10:58 UTC
it hangs after opening the browser, is that normal?

**Comment by jakub-g** [comment] 2015-04-12 12:58
I've just checked and indeed when you use it like that
`biased-opener -b 'chrome' http://example.org`
it may not return control to the shell. You can add ampersand at the end to give back the control to the shell:
`biased-opener -b 'chrome' http://example.org &`

The issue is that under the hood I delegate to `opener` to open default browser (this returns to shell immediately) but for non-default browser I delegate to `browser-launcher2` and this call does not return to shell.

I'll see what I can do.

**Comment by jakub-g** [comment] 2015-04-13 09:34
@chovy can you tell exactly which platform, and which browser are causing this?

**Comment by anthonyettinger** [comment] 2015-04-13 23:34
mac/safari

**Comment by jakub-g** [comment] 2015-04-17 08:31
should be fixed in 0.2.5, please let me know

**Closed as completed** 2015-04-17 08:31 UTC
